### ISSUE TITLE
Implement LOADKX opcode

### ISSUE THREAD

**Issue by Leonardo2718** [Leonardo2718/lua-vermelha#11]
Implement ILGen for the LOADKX opcode as well as adequate testing.

**Comment by charliegracie** [comment]
Have you come across any programs that generate a LOADKX instruction?  At the moment I can only generate a function at runtime and then call it.  The issue is that it takes 10+ minutes for the lua program to generate the function which tests LOADKX.  I am not sure that it is reasonable for such a  simple test to require 10+ minutes.

**Comment by Leonardo2718** [comment]
I have actually run into a program that generated a `LOADKX`.

I admit that there likely isn't a small test case that will generate it. I did manage the create one that generates it and executes in less than one second. It's large, but it seems to do the job.

The opcode itself is simple enough to implement. I am really more interested in handling the `EXTRAARG` opcode. Some of the other opcodes may require a similar mechanism to be implemented (for performance reasons, though I haven't verified this hypothesis). `LOADKX` just seems like a simple test case.

Currently, my guess is that several JIT optimizations are simply going to give up when dealing with a function large enough to have a `LOADKX`. However, once some better JIT control mechanisms are in place, there will be more room to perform better optimizations. At that point, being able to handle `LOADKX` could be worthwhile.

I know I'm probably thinking about the future too much but, as I mentioned, `LOADKX` is simple enough.

**Comment by Leonardo2718** [comment]
Upon further consideration, I've decided that this opcode is not worth implementing so I'm closing this issue.
