### ISSUE TITLE
Chinese translation of the document

### ISSUE THREAD

**Issue by leejingbo** [Leonardo2718/lua-vermelha#25]
I cloned the repo and made some Chinese translation of the document.

Could I make pull requests for this ?

**Comment by Leonardo2718** [comment]
Yes! I'd be happy to see the documentation translated. (Sorry for the late reply BTW)

The PR should be reviewed by someone who actually knows Chinese though. @xliang6, would you mind reviewing the PR for me (once it's open)?

**Comment by xliang6** [comment]
@Leonardo2718 I'd be happy to review the translation. Thanks @leejingbo!
